### Student Name: Mohamed Ahmed Mohamed Abo El-Enen

### Q1

In [ ]:
import numpy as np

In [ ]:
M = np.array([[0,1],[-2,-3]])

In [ ]:
np.linalg.eig(M)

(array([-1., -2.]),
 array([[ 0.70710678, -0.4472136 ],
        [-0.70710678,  0.89442719]]))

### Q2

In [ ]:
import sympy as sym

In [ ]:
lambda_symbol = sym.Symbol('lambda')

In [ ]:
def get_matrix_dim(matrix):
    return matrix.shape

In [ ]:
def define_identity_matrix(row, col):
    idt_matrix = np.zeros((row,col))
    for r in range(row):
        for c in range(col):
            if r == c:
                idt_matrix[r,c]=1
    
    #np.eye(row)
    return idt_matrix

In [ ]:
def define_lambda_identity_matrix(idt_matrix):
    idt_matrix = lambda_symbol * idt_matrix       
    return idt_matrix

In [ ]:
def subtract_lambda_from_matrix(matrix, idt_matrix):
    matrix = matrix - idt_matrix       
    return matrix

In [ ]:
def get_eigen_vector(eigen_values, lambda_matrix, dim):
    res = []
    for value in list(eigen_values):
        tmp = sym.Matrix(lambda_matrix).subs({lambda_symbol:value})
        zeros = np.zeros((dim, 1))        
        res.append(tmp.rref()[0])
    return res

In [ ]:
def vector_assumtion(eigen_vectors, dim):
    list_x = []
    for i in range(1,dim+1):
        list_x.append(sym.Symbol("x"+str(i)))
    return np.array(list_x)

In [ ]:
def vector_assumtion_relation(eigen_vectors, vectors_assumtion):
    vector_rel_list = []
    for i in range(0, len(eigen_vectors)):
        res = sym.Matrix(eigen_vectors[i]) @ sym.Matrix(vectors_assumtion)
        tmp_list = []
        for x in vectors_assumtion:
            tmp_list.append(sym.solve(res, x))
            
        vector_rel_list.append((f"eigen vector {i+1} relation", tmp_list))
        
    return vector_rel_list

In [ ]:
def get_eigen_values_vectors(matrix):
    row, col = get_matrix_dim(matrix)
    if row != col:
        print("Not A Squared Matrix")
        return None
    idntity_matrix = define_identity_matrix(row, col)
    lambda_idntity_matrix = define_lambda_identity_matrix(idntity_matrix)
    lambda_matrix = subtract_lambda_from_matrix(matrix, lambda_idntity_matrix)
    determinant_func = sym.Matrix(lambda_matrix).det()
    eigen_values = sym.solve(determinant_func, lambda_symbol)
    eigen_vectors = get_eigen_vector(eigen_values, lambda_matrix, col)
    vectors_x = vector_assumtion(eigen_vectors, row)
    vectors_x = vector_assumtion_relation(eigen_vectors, vectors_x)
    return eigen_values, np.array([np.array(v) for v in eigen_vectors]), vectors_x

In [ ]:
matrix = np.array([[0, 1],
                   [-2, -3]])

eigen_values, eigen_vectors, vectors_x = get_eigen_values_vectors(matrix)
print("Eigen Values: ", eigen_values)
print("Eigen Vector: ", eigen_vectors)
print("Eigen Vector Relations: ", vectors_x, sep = "\n")

Eigen Values:  [-2.00000000000000, -1.00000000000000]
Eigen Vector:  [[[1 0.500000000000000]
  [0 0]]

 [[1 1.00000000000000]
  [0 0]]]
Eigen Vector Relations: 
[('eigen vector 1 relation', [{x1: -0.5*x2}, {x2: -2.0*x1}]), ('eigen vector 2 relation', [{x1: -x2}, {x2: -x1}])]


### Q3

In [ ]:
def Get_PCA(data_matrix, n_pca):
    
    mean_matrix = np.mean(data_matrix, axis=0)
    diff_matrix = (data_matrix - mean_matrix)

    covariance_matrix = np.cov(diff_matrix.T)
    values, vectors = np.linalg.eig(covariance_matrix)
    sorted_index = np.argsort(values)[::-1]
    
    list_vec = []
    list_val = []
    for i in range(n_pca):
        list_vec.append(vectors[:,sorted_index[i]])
        list_val.append(values[sorted_index[i]])
    pca_matrix = np.array(list_vec)
    
    print("Eigen Values: ", list_val, sep = "\n")
    print("PCA Matrix: ", pca_matrix, sep = "\n")
    pca_new_feat = pca_matrix.dot(diff_matrix.T)
    return pca_new_feat.T

In [ ]:
data_matrix = np.array([[1,2,3,4], 
                        [5,5,6,7],
                        [1,4,2,3],
                        [5,3,2,1],
                        [8,1,2,2]])

n_pca = 2

In [ ]:
print("PCA new features: ", Get_PCA(data_matrix, n_pca), sep = "\n")

Eigen Values: 
[10.606630504517529, 7.908086969903933]
PCA Matrix: 
[[ 0.69478464 -0.34820806 -0.32341225 -0.53984254]
 [-0.69892736 -0.17035429 -0.47997101 -0.50210337]]
PCA new features: 
[[-2.06005139  1.96587434]
 [-2.91530135 -4.2871211 ]
 [-1.89321273  2.60724014]
 [ 2.31381898  0.98609174]
 [ 4.55474649 -1.27208513]]


In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_pca)

pca.fit(data_matrix)

print("pca components", pca.components_, sep = "\n")
print("pca variance ", pca.explained_variance_, sep = "\n")

pca_new_fet = pca.transform(data_matrix)
print("pca new features ", pca_new_fet, sep = "\n")

pca components
[[ 0.69478464 -0.34820806 -0.32341225 -0.53984254]
 [ 0.69892736  0.17035429  0.47997101  0.50210337]]
pca variance 
[10.6066305   7.90808697]
pca new features 
[[-2.06005139 -1.96587434]
 [-2.91530135  4.2871211 ]
 [-1.89321273 -2.60724014]
 [ 2.31381898 -0.98609174]
 [ 4.55474649  1.27208513]]


### Q4

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [ ]:
scaler = StandardScaler()
data_matrix_sts = scaler.fit_transform(data_matrix)

pca = PCA(n_pca)
pca_new_fet_sts = pca.fit_transform(data_matrix_sts)

In [ ]:
print("pca components ", pca.components_, sep = "\n")
print("pca variance ",pca.explained_variance_, sep = "\n")
print("pca new features ", pca_new_fet_sts, sep = "\n")

pca components 
[[-0.16195986  0.52404813  0.58589647  0.59654663]
 [-0.91705888  0.20692161 -0.3205394  -0.11593512]]
pca variance 
[3.14474155 1.33161063]
pca new features 
[[-1.56561741e-02  8.45205482e-01]
 [ 2.85829190e+00 -8.72549250e-01]
 [ 5.75566043e-02  1.40104719e+00]
 [-1.13385419e+00  2.66995807e-04]
 [-1.76633814e+00 -1.37397042e+00]]


In [ ]:
pca_new_fet_sts

array([[-1.56561741e-02,  8.45205482e-01],
       [ 2.85829190e+00, -8.72549250e-01],
       [ 5.75566043e-02,  1.40104719e+00],
       [-1.13385419e+00,  2.66995807e-04],
       [-1.76633814e+00, -1.37397042e+00]])